import { Package, Globe } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

interface Props {
  data: {
    name: string;
    slug: string;
    sellerSku: string;
    partNumber: string;
    hsCode: string;
    unspsc: string;
    ntn: string;
    barcode: string;
    modelNumber: string;
    summary: string;
    description: string;
  };
  onChange: (data: Partial<Props["data"]>) => void;
  slugDisabled?: boolean;
  systemSku?: string;
}

export function BasicInfoStep({ data, onChange, slugDisabled = false, systemSku }: Props) {
  const field = (
    label: string,
    key: keyof Props["data"],
    placeholder: string,
    options?: { className?: string; type?: string; optional?: boolean },
  ) => (
    <div className="space-y-1.5">
      <Label className="text-sm font-medium text-gray-700 dark:text-gray-300">
        {label}
        {options?.optional && (
          <span className="ml-1 font-normal text-gray-400">(optional)</span>
        )}
      </Label>
      <Input
        value={data[key] as string}
        onChange={(e) => onChange({ [key]: e.target.value })}
        placeholder={placeholder}
        type={options?.type ?? "text"}
        className={`h-11 ${options?.className ?? ""}`}
      />
    </div>
  );

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-100 dark:bg-blue-900/30">
          <Package className="h-5 w-5 text-blue-600 dark:text-blue-400" />
        </div>
        <div>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Basic Information</h2>
          <p className="text-sm text-gray-500 dark:text-gray-400">Enter your product details</p>
        </div>
      </div>

      {/* Primary */}
      <div className="space-y-1.5">
        <Label className="text-sm font-medium text-gray-700 dark:text-gray-300">
          Product name <span className="ml-1 text-red-500">*</span>
        </Label>
        <Input
          value={data.name}
          onChange={(e) => onChange({ name: e.target.value })}
          placeholder="Wireless Bluetooth Headphones"
          className="h-11"
        />
      </div>

      <div className="space-y-1.5">
        <Label className="text-sm font-medium text-gray-700 dark:text-gray-300">Product slug</Label>
        <div className="relative">
          <Globe className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />
          <Input
            value={data.slug}
            onChange={(e) => onChange({ slug: e.target.value.toLowerCase().replace(/\s+/g, "-") })}
            placeholder="auto-generated"
            disabled={slugDisabled}
            className="h-11 pl-10 disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500 dark:disabled:bg-gray-800 dark:disabled:text-gray-400"
          />
        </div>
        <p className="text-xs text-gray-400 dark:text-gray-500">Auto-generated from product name</p>
      </div>

      {/* System SKU — read-only, generated by the backend */}
      <div className="space-y-1.5">
        <Label className="text-sm font-medium text-gray-700 dark:text-gray-300">System SKU</Label>
        <Input
          value={systemSku ?? ""}
          placeholder="Auto-generated on save (e.g. HTA-EL-2608-000001)"
          disabled
          className="h-11 font-mono disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500 dark:disabled:bg-gray-800 dark:disabled:text-gray-400"
        />
        <p className="text-xs text-gray-400 dark:text-gray-500">
          Generated by the system from organization, category, and date. Not editable.
        </p>
      </div>

      {/* Identification codes */}
      <div className="grid gap-4 sm:grid-cols-2">
        {field("Seller SKU", "sellerSku", "e.g. MY-SKU-001", { optional: true })}
        {field("Part Number", "partNumber", "PN-001", { optional: true })}
        {field("HS Code", "hsCode", "8471.30", { optional: true })}
        {field("UNSPSC", "unspsc", "43211500", { optional: true })}
        {field("NTN", "ntn", "1234567-8", { optional: true })}
        {field("Barcode", "barcode", "EAN / UPC", { optional: true })}
        {field("Model Number", "modelNumber", "Model X", { optional: true })}
      </div>

      {/* Summary & description */}
      {field("Summary", "summary", "High-quality wireless headphones with noise cancellation", { optional: true })}

      <div className="space-y-1.5">
        <Label className="text-sm font-medium text-gray-700 dark:text-gray-300">
          Description <span className="ml-1 font-normal text-gray-400">(optional)</span>
        </Label>
        <Textarea
          value={data.description}
          onChange={(e) => onChange({ description: e.target.value })}
          placeholder="Detailed product description..."
          rows={4}
          className="resize-none"
        />
      </div>
    </div>
  );
}
